### ISSUE TITLE
Formspree no longer works with just an email address

### ISSUE THREAD

**Issue by Lextuga007** [hugo-apero/hugo-apero#10]
When I was setting up the form I found Formspree asks you to set up an account and eventually I found this: https://help.formspree.io/hc/en-us/articles/360056076314 which explains the prompt.

Once an account and a form is set up (free plan allows for 2 emails and its within Formspree that I selected which email I wanted to receive the messages to) I changed the formspree_form_id:  in content\form to https://formspree.io/f/CodeGeneratedByFormspree".  I then changed the themes\hugo-apero\layouts\partials\shared\contact-form.html to the suggested Formspree code.

For the hugo-apero theme I kept the themes\hugo-apero\layouts\partials\shared\contact-form.html but needed to add /f/ to the https://formspree.io url. I then only needed the CodeGeneratedByFormspree for the  content\form formspree_form_id:

I hope that makes sense and is helpful.

**Comment by apreshill** [comment]
thank you! Sounds like I definitely need to rework that layout file.

**Comment by Lextuga007** [comment]
Would it help if I made changes that got mine to work and do a pull request or are you wanting to rework it completely?

**Comment by apreshill** [comment]
That would be amazing, and would definitely help me figure out if anything else needs to change!

**Comment by apreshill** [comment]
fixed with https://github.com/hugo-apero/hugo-apero/pull/11
