### ISSUE TITLE
About Page 404 Error

### ISSUE THREAD

**Issue by DrJohan** [hugo-apero/hugo-apero#108]
Hi @apreshill . I've been trying to built a new website using this theme. However, after following all the steps that you've mentioned in your blog [post](https://hugo-apero-docs.netlify.app/start/create-site/), I noticed that whenever I click the About menu button, 404 error will show up. I've checked the directory and all files and folders is there where it should be. Here is the link to my [repo](https://github.com/DrJohan/testhugo) for your reference. Any help will be much appreciated. Thanks!!!

**Comment by mcsnowface** [comment]
Hi @yihui and @apreshill - I experience the same issue as @DrJohan . Any ideas what the problem could be?

**Comment by MWillian** [comment]
Hello @apreshill @yihui @DrJohan @mcsnowface, i was working in a project using the Hugo theme, and facing the same issue when starting the site in local host, receiving the 404 error page when clicked in the About page. Searching the solution on the archives, i tried to change the value of the **Headless** field to **false**, in the _index.md file located in the **/about/** folder.

![print rstudio](https://github.com/hugo-apero/hugo-apero/assets/101839061/b29b88ef-9e56-4397-bc56-54bcb813785c)

**Comment by mcsnowface** [comment]
@MWillian yes, that fixed it! It works for me now as well. I think you also posted an "answer" on my question here: https://stackoverflow.com/questions/78130361/about-page-not-working-when-using-a-fresh-hugo-apero-build/78211460#78211460
Please edit your answer and saying that the fix is to set `headless: false`. Then I will accept you answer as the solution :)

**Comment by MWillian** [comment]
@mcsnowface  I'm going to edit my answer in the Stackoverflow thread. I just noticed that I was too short with my words there, and if this problem persists in the project's base code, other people will struggle with the same thing. Have a great day buddy!
