### ISSUE TITLE
missing static/ folder in project root

### ISSUE THREAD

**Issue by vrbiki** [hugo-apero/hugo-apero#35]
I've created my site in blogdown using:
`blogdown::new_site(theme = "hugo-apero/hugo-apero", format = "toml", sample = FALSE)`
I am confused that it creates the static/ folder in /themes/hugo-apero/static. That is to say, there is no static/ folder in my project root. I've tried to create a static folder in the project root and move the landing page image (image /themes/hugo-apero/static/img/revoir.jpg) there; however, I don't know how to reroute Hugo to look for the image in this newly created static/ folder.

**Comment by bennour007** [comment]
I find this confusing as well, I created a static folder in the root path, but it doesn't seem to be recognised while serving the website, is there any kind of references about this in apéro I can check, or is there a change I'm not aware of?

**Comment by apreshill** [comment]
> I am confused that it creates the static/ folder in /themes/hugo-apero/static.

This folder is part of the theme. All of Hugo works by overriding things in the `themes/` older with project root folders. You don't need to re-route anything.

> I find this confusing as well, I created a static folder in the root path, but it doesn't seem to be recognised while serving the website, is there any kind of references about this in apéro I can check, or is there a change I'm not aware of?

This works for me on the docs site and all my sites too? https://github.com/hugo-apero/hugo-apero-docs/tree/main/static/img

https://github.com/rbind/apreshill/tree/main/static

https://github.com/rstudio-education/iyo-rstudio-global/tree/main/static

Happy to update the docs, but not sure what would have made a difference here? https://hugo-apero-docs.netlify.app/start/site-config/#ap%c3%a9ro-variables

**Comment by vrbiki** [comment]
I was unfortunately never able to figure out how to correctly set up a static folder in the root of the hugo-apero website created using the `blogdown::new_site` function. The way that I avoided the problem was to pull the starter repo for the "Introduce Yourself Online" workshop and begin to edit that.  To recreate the issue one can do the following:
1. Execute `blogdown::new_site(theme = "hugo-apero/hugo-apero", format = "toml", sample = FALSE)`
2. Create a `static/` directory in the root with a subdirectory `img/`
3. Copy the contents of the original `img` directory to the newly created folder: `cp -R /themes/hugo-apero/static/img/ static/img/`
4. Add the image `foo.jpg` into  `/static/img/`
5. Edit the `/content/_index.md` to have the image `img/foo.jpg` (instead of `img/revoir.jpg`). Save
6. `blogdown::serve_site()`
If you follow those steps, you will see that the landing page has a broken image icon.  I hope that is somewhat helpful.

**Comment by apreshill** [comment]
Thank you so much @vrbiki! Unfortunately I cannot reproduce. When I follow these steps I see:

<img width="1402" alt="Screen Shot 2021-07-21 at 12 06 17 PM" src="https://user-images.githubusercontent.com/12160301/126545550-2fc700f9-2c70-4789-9ee3-5f39c912b07d.png">

**Comment by apreshill** [comment]
FYI you can have blogdown create the empty folders for you in the project root:
<img width="667" alt="Screen Shot 2021-07-21 at 12 25 14 PM" src="https://user-images.githubusercontent.com/12160301/126547963-c153a835-31b5-41d1-80ce-2283b955c8d7.png">

At the command line: `blogdown::new_site(theme = "hugo-apero/hugo-apero", format = "toml", sample = FALSE, empty_dirss = TRUE)`

**Comment by bennour007** [comment]
I'm not sure if asking this is appropriate or not, but 

> This works for me on the docs site and all my sites- if you fix it, will you let me know what the issue was?
> 
> https://github.com/hugo-apero/hugo-apero-docs/tree/main/static/
> 
> https://github.com/rbind/apreshill/tree/main/static
> 
> https://github.com/rstudio-education/iyo-rstudio-global/tree/main/static
> 
> I want to be responsive here, but not sure what would have made a difference in the docs? https://hugo-apero-docs.netlify.app/start/site-config/#ap%c3%a9ro-variables
> 
> PRs for improvements to the docs are definitely welcome!

Thank you for your reply, I noticed in your personal website you have a pdf folder in your static, I originally wanted to do is to link a menu tab(resume) directly to a pdf file, and placed that in a static folder I created in root directory, I specified the file path in the config.toml, but I'm not sure if I need to create a directory for that menu tab in the content folder, and what arguments the _index.md file should have if yes.

**Comment by apreshill** [comment]
Closing since not able to repro bug, and no response from original author. Happy to reopen discussion in a new issue for suggestions on improving the docs 📝
