### ISSUE TITLE
Switch the hyperlink order on Collections

### ISSUE THREAD

**Issue by Lextuga007** [hugo-apero/hugo-apero#5]
Could there be a way to setting the positioning of the links at the bottom of a collection in Hugo Apéro, as currently it has the folder-before link on the left and I'd prefer it to be on the right? As an example: https://iyo-rstudio-global.netlify.app/collection/day01/03-distill/ 

Many thanks

**Comment by apreshill** [comment]
Thank you! Pinning this forum thread as I think it will help me: https://discourse.gohugo.io/t/nextinsection-with-nested-sections-with-menu-in-config-yaml/18226/15
