### ISSUE TITLE
Create new post

### ISSUE THREAD

**Issue by xiaochi-liu** [hugo-apero/hugo-apero#50]
Hello. I'm using the `blogdown` addin to create a new blog post:

![Screen Shot 2021-09-11 at 12 05 28](https://user-images.githubusercontent.com/48895627/132932774-f2b46a01-ce7b-42ad-bf31-7c57bffebb54.png)

May I ask, how to choose the `Archetype`？

And what's the difference between using `.Rmd` or `.Rmarkdown`?

**Comment by harshvardhaniimi** [comment]
[Archetypes define the "look-and-feel" of the webpages](https://www.apreshill.com/blog/2019-02-spoonful-archetypes/). In Hugo Apero, blog/ looks different from talk/ which looks different from project/ (although all are customisable). Blog-like pages show title and usually a sidebar with estimated reading time. Talk-like pages have external links like link to a Github repo or slides. They are different from subdirectory. You can have a talk-like page in your collection of blog posts.

There are two major differences between .Rmd and .Rmarkdown. .Rmd may not support list of tasks; .Rmarkdown may not support MathJax. For more details, see [Blogdown Chapter 1.5](https://bookdown.org/yihui/blogdown/output-format.html).

**Comment by harshvardhaniimi** [comment]
**If your issue has been resolved, please close the issue.**

**Comment by xiaochi-liu** [comment]
Thank you very much, @harshvardhaniimi. This guidance is fantastic.
