### ISSUE TITLE
How to use google analytics 4?

### ISSUE THREAD

**Issue by SantiDu** [hugo-apero/hugo-apero#52]
If I want to use google analytics 4, should I just change 
```
{{ template "_internal/google_analytics_async.html" . }}
```
from layouts/partials/head.html
to
```
{{ template "_internal/google_analytics.html" . }}
```
or there's more I need to do?

**Comment by harshvardhaniimi** [comment]
Fixed it via [this](https://github.com/hugo-apero/hugo-apero/pull/59) pull request. You could use both statements in [layouts/partials/head.html](https://github.com/hugo-apero/hugo-apero/blob/main/layouts/partials/head.html) and that will fix all of it.
