### ISSUE TITLE
Hugo-Apero formspree and google scholar logo

### ISSUE THREAD

**Issue by BB1464** [hugo-apero/hugo-apero#55]
Hi Dear All,
I am using the hugo Apero theme in blogdown to build my static website, and I have registered for the formspree but when I build the site it is still telling me form not found and also I will like to add google scholar to my yaml file. Please how can I achieve this? here is the link to the site:
https://clever-perlman-5a941b.netlify.app/

Thank you!!!

**Comment by harshvardhaniimi** [comment]
Hey @BB1464, the site link you provided doesn't work anymore. 

You will have to change the way you make your Formspree form. Unlike putting the email directly, you will have to create an account on Formspree and then proceed. [See this.](https://help.formspree.io/hc/en-us/articles/360056076314-Phasing-out-legacy-forms-email-URLs-)

For adding Google Scholar, I'm not sure what do you mean. Can you elaborate?

**Comment by BB1464** [comment]
@harshvardhaniimi thank you for your response, what I mean is that when I try to add the google scholar icon to my sites it does not show the icon on the sites.

**Comment by harshvardhaniimi** [comment]
The theme borrows icons available at [Font Awesome for free](https://fontawesome.com/v5.15/icons?d=gallery&p=1&s=brands&m=free). As you can check there, Google Scholar doesn't have any freely available icon. I use a solid [graduation cap](https://fontawesome.com/v5.15/icons/graduation-cap?style=solid) icon. Here's my [config.toml](https://github.com/harshvardhaniimi/personal-website/blob/main/config.toml).

**Comment by BB1464** [comment]
@harshvardhaniimi thank you for your help, I really appreciate it.
