### ISSUE TITLE
How to Use this Theme?

### ISSUE THREAD

**Issue by joesan** [hugo-apero/hugo-apero#65]
I'm currently having my blog bigelectrons.com using Zola and a theme, but I see that there is very less progress on the issues that are fixed. So I'm thinking of moving elsewhere and I see this to be really interesting and having most of the features that I might want. 

I however do not see any documentation on how to use this theme. Could someone point me on how to use this there with my content? I would be thankful.

**Comment by apreshill** [comment]
Hi there,

Here is the documentation site: https://hugo-apero-docs.netlify.app/

Can you let me know where you looked? I'd love to make the docs easier to find! 

There are also some YouTube videos for workshops I've done with the theme here: https://www.youtube.com/playlist?list=PLzxicn7kBeay3kTPuTQ9lSi7I5jfWmEwc (linked to in the YouTube link on the docs site)

Alison
