### ISSUE TITLE
Contact form integration with formspree doesn't work

### ISSUE THREAD

**Issue by erinmr** [hugo-apero/hugo-apero#67]
Hi - The formspree integration isn't working for me when I put my email address in on contact.md page ([my contact page](https://erinrobinson.info/contact/). It seems like the method is being [phased out by formspree](https://help.formspree.io/hc/en-us/articles/360056076314). Is there a way to connect to a specific form in Formspree? 

Thanks!

**Comment by mccarthy-m-g** [comment]
You need to use the form ID from your form’s URL.

On the integration page for your form on Formspree you get a form endpoint URL that looks like this: `https://formspree.io/f/myformid`. The string that’s in the place of `myformid` here is what you want to put in the `formspree_form_id` field in `contact.md`.

**Comment by apreshill** [comment]
@erinmr did this fix your issue?

This was fixed in https://github.com/hugo-apero/hugo-apero/pull/11

But looks we need to update the docs here to match: https://hugo-apero-docs.netlify.app/learn/built-in-contact-form/

**Comment by erinmr** [comment]
Thanks for responding @mccarthy-m-g and @apreshill my issue was that I'd included the f/ with the form ID. I just took that out and everything worked like a charm!
