### ISSUE TITLE
`Page.UniqueID` will be removed in Hugo 0.93.0

### ISSUE THREAD

**Issue by KHwong12** [hugo-apero/hugo-apero#76]
First thing first, thanks for making this splendid template!

I tried to build and test the example site using `hugo server -D` and the following error appears.

```
ERROR  Page.UniqueID is deprecated and will be removed in Hugo 0.93.0. Use .File.UniqueID
```

With a quick grep I found the partial using the `.UniqueID` variable is `breadcrumb.html`.

https://github.com/hugo-apero/hugo-apero/blob/5a68e286ff017bd55d0be4a93ee1a421f9ee6c39/layouts/partials/shared/breadcrumb.html#L2-L11

As of Feb 2022, [hugo is now v0.92.2](https://github.com/gohugoio/hugo/releases/tag/v0.92.2).

I have no experience in writing shortcodes and do not understand much about layout templates. I am not sure how to remove the error, sorry about that.

**Comment by KHwong12** [comment]
FWIW my current dump way to work-around the error is to remove the `.UniqueID` variable and the if statement, making the title always be a hyperlink.

```
<h4 class="breadcrumb pb5">
{{ template "breadcrumb" dict "currentPage" .Page }}
</h4>

<!-- templates -->
{{ define "breadcrumb" }}
  {{ if .currentPage.Parent }}
    {{ if ne .currentPage.Parent .IsHome }}
      {{ template "breadcrumb" dict "currentPage" .currentPage.Parent }}
    {{ end }}
      <a href="{{ .currentPage.RelPermalink }}">{{ .currentPage.Title }}</a>
  {{ end }}
{{ end }}
```

**Comment by KHwong12** [comment]
Thanks for letting me know the method of pinning Hugo version! Have not thought about that before.

**Comment by cderv** [comment]
Regarding pinning Hugo version for a blogdown project, you can also look here for option in R profile, and how to install several hugo versions
https://www.rstudio.com/blog/blogdown-v1.0/#hugo-versioning-system

**Comment by cderv** [comment]
And regarding the fix, Hugo syntax is now `.Page.File.UniqueID` instead of `.Page.UniqueID`. This should be updated in the template file however, this could create a minimum requirement to Hugo version. But probably 0.70 (as it seems .File.UniqueID have been introduced in 4bdc9bc72)

**Comment by KHwong12** [comment]
Thanks for pointing out the way to fix it! Changed the shortcode variables as below and the error message is now gone.

```
<h4 class="breadcrumb pb5">
{{ template "breadcrumb" dict "currentPage" .Page "id" .File.UniqueID }}
</h4>

<!-- templates -->
{{ define "breadcrumb" }}
  {{ if .currentPage.Parent }}
    {{ if ne .currentPage.Parent .IsHome }}
      {{ template "breadcrumb" dict "currentPage" .currentPage.Parent }}
    {{ end }}
    {{ if eq .id .currentPage.File.UniqueID }}
      {{ .currentPage.Title }}
    {{ else }}
      <a href="{{ .currentPage.RelPermalink }}">{{ .currentPage.Title }}</a>
    {{ end }}
  {{ end }}
{{ end }}
```

**Comment by cderv** [comment]
You can probably open a PR with this fix then :) Thanks !

**Comment by KHwong12** [comment]
@cderv Sure! And just want to say a huge thanks to you for maintaining rmarkdown and many other packages :)
