### ISSUE TITLE
Does Hugo Apero support interactive elements?

### ISSUE THREAD

**Issue by uriahf** [hugo-apero/hugo-apero#80]
Hi!

I want to create a new blog and I'm considering using Hugo Apero.
Thing is, I'm a heavy user of plotly, reactable and crosstalk. Does Hugo Apero works well with these packages?

Thanks!

**Comment by harshvardhaniimi** [comment]
I have used [Plotly](https://www.harsh17.in/how-much-do-we-know-about-our-ancestors/), [DT](https://www.harsh17.in/number-of-phds/) and [Shiny](https://www.harsh17.in/is-covid-19-data-tampered/) on my website. They work great on laptops, but the view is sometimes distorted in mobile view.

**Comment by uriahf** [comment]
Thanks, that's helpful! 
I'll give it a try and share the results.
