### ISSUE TITLE
Can't see the images on "talk" section

### ISSUE THREAD

**Issue by uriahf** [hugo-apero/hugo-apero#83]
Hi! 
Thank you for this wonderful platform! 

I'm working on my own blog and I think that something I did make the small images on the talk section disappear.

I used some of the default examples and it looks like this:

![screenshot-rtichoke-blog netlify app-2022 05 17-15_42_45](https://user-images.githubusercontent.com/11351434/168813576-14df1f29-7dc4-4ac8-8a1f-a1fadb76ed86.png)

Link for my code:
https://github.com/uriahf/rtichoke_hugo/tree/main/content/talk

This is the link for the rendered section:
https://rtichoke-blog.netlify.app/talk

**Comment by lisalevinson** [comment]
It seems like you're missing the section config page (_index.md) for that section.

**Comment by uriahf** [comment]
How silly of me, you're right! It's fixed now :)
