### ISSUE TITLE
Blogdown serve_site, page could not load, after changing in config.toml

### ISSUE THREAD

**Issue by CongWang141** [hugo-apero/hugo-apero#87]
I have some problems creating my website using the theme hugo-apero. When I change something in config.toml the page could not load, with error:

Failed to reload config: "D:\ComputationalTool\RStudy\congwang\hugo_apero\config.toml:10:42": unmarshal failed: toml: invalid character in comment .

Even if I undo the changes and return to the original, there will be the same error. I could not reload the page anyhow.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/110236467/185786371-912edbde-8b97-45c7-ab19-e767285c4107.png)

In addition: Warning message:
In read_utf8(file) :
The file config.toml is not encoded in UTF-8. These lines contain invalid UTF-8 characters: 10

So I think maybe that is the problem, but I still don't know how to solve it.

**Comment by cderv** [comment]
This has also been posted in https://community.rstudio.com/t/blogdown-serve-site-page-could-not-load/145332/4

Issue seems to be this line 
https://github.com/hugo-apero/hugo-apero/blob/8aabd8954f3650f3bd7787b4e31e3c590d94ea96/exampleSite/config.toml#L10

When the theme is installed on the user environment, the special character seems to have been modified. Probably an encoding issue. 

Something in **blogdown** installation function ? or we should just avoid using this special character here ?

**Comment by CongWang141** [comment]
> This has also been posted in https://community.rstudio.com/t/blogdown-serve-site-page-could-not-load/145332/4
> 
> Issue seems to be this line (see in comment at end of the line)
> 
> https://github.com/hugo-apero/hugo-apero/blob/8aabd8954f3650f3bd7787b4e31e3c590d94ea96/exampleSite/config.toml#L10
> 
> When the theme is installed on the user environment, the special character seems to have been modified. Probably an encoding issue.
> 
> Something in **blogdown** installation function ? or we should just avoid using this special character here ?

Not only this theme but when I use several other themes the same thing happened. Some strange words will pomp out. So probably something in blogdown is wrong. Then I tried to modify the config.toml file in Visual Studio Code, there is no such problem there, everything works just fine.

**Comment by cderv** [comment]
@yihui we should maybe check the encoding used when reading / writing the file but usually we are enforcing UTF-8. Maybe not in one place ?

**Comment by yihui** [comment]
@CongWang141 Could you provide your `xfun::session_info('blogdown')`? If you are using Windows 10 (November 2019 update) or newer, you shouldn't run into encoding problems any more, since UTF-8 has become the default encoding of R. I can't think of a possible reason that your `config.toml` is modified with the wrong character encoding. You may try to copy `config.toml` from https://github.com/hugo-apero/hugo-apero/blob/main/exampleSite/config.toml and paste the content into your editor.

BTW, make sure your encoding setting in RStudio is also UTF-8: Tools -> Project Options or Global Options -> Code -> Saving -> Default text encoding -> UTF-8.

**Comment by CongWang141** [comment]
> @yihui  Thanks for the advice, I have changed the Default text encoding to UTF-8, and now it works just fine with hugo-apero.  For curiosity, I try to modify another theme(zhaohuabing/hugo-theme-cleanwhite) the same thing happened again. 
![image](https://user-images.githubusercontent.com/110236467/186003672-cd744b15-781f-4b63-bd71-9c09fbf22ac2.png)
But now I am happy it works with hugo-apero. Thanks!

**Comment by yihui** [comment]
Great!

Could you zip the `hugo-zhaohuabing` folder and upload it here?

**Comment by CongWang141** [comment]
[hugo-zhaohuabing.zip](https://github.com/hugo-apero/hugo-apero/files/9397950/hugo-zhaohuabing.zip)
Here you go, above is the file with errors, the original theme can be found [here](https://github.com/zhaohuabing/hugo-theme-cleanwhite).

**Comment by yihui** [comment]
The RStudio project option is `Encoding: CP936`. It should be UTF-8 instead.

As I first replied above, you need to configure the global encoding option as UTF-8. After that, when you create new projects, this option will be inherited. I guess you didn't configure this option before, therefore you ran into the encoding issue in new blogdown projects.
