### ISSUE TITLE
audio.m4a for saying name doesn't work

### ISSUE THREAD

**Issue by Lextuga007** [hugo-apero/hugo-apero#9]
In content/about/sidebar I've set the show_audio_link: true and tried both the audio.m4a and audio.mp3 format but neither work. My code is: https://github.com/Lextuga007/Philosopher-Analyst-Netlify/blob/main/content/about/sidebar/index.md

The example for this site is m4a too and most voice recorders default to mp3 so I had to convert it online. Is it possible to use different formats?

Many thanks and I hope it's ok that I keep raising so many issues! I'm really enjoying exploring this code.

**Comment by apreshill** [comment]
Thank you! Let me take another look at this- it worked *at some point* but something obviously has changed! Grrr

**Comment by apreshill** [comment]
So I think the best solution will involve having a named file like `audio*` and letting Hugo page resources take over to find the file path. In testing this out, this seems like the most foolproof approach.

**Comment by apreshill** [comment]
Sorry for the delay on this @Lextuga007! But I believe this should be fixed now. The catch is that I had to edit the sidebar YAML slightly:

https://github.com/hugo-apero/hugo-apero/blob/main/exampleSite/content/about/sidebar/index.md

**Comment by Lextuga007** [comment]
That's ok and thank you! It works. I copied over the layouts\about\list.html as well as changing the line in exampleSite/content/about/sidebar/index.md to audio_link_label: "How to say my name" # leave blank to exclude and it works with .m4a format! Much appreciated.
