### ISSUE TITLE
Unknown error when using serve_site()

### ISSUE THREAD

**Issue by nacefbm** [hugo-apero/hugo-apero#90]
Hi, 

I was working locally on my site (changing the about section) and I suddenly got an error when I do type the serve_site() command. I don't know how to resolve it and since then I'm blocked.

here is the error : 
Error building site: failed to render pages: render of "section" failed: "/Users/User/Documents/1er site/themes/hugo-apero/layouts/talk/list.html:10:21": execute of template failed: template: talk/list.html:10:21: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages

what can I do to retrieve safely my broken site ?

Thank you

I've also tried the check site command.

**Comment by apreshill** [comment]
Hi sorry- I cannot troubleshoot this issue as reported. If you want to provide some more information I can see if I can help! Closing for now...
